#!/bin/bash

volume="$(mpc volume | awk '{print $2}')"
current_title="$(mpc current | awk -F ' - ' '{print $2}')"

if [ -n "$volume" ] && [ -n "$current_title" ]; then
    title="$volume - $current_title"
    echo "^c#cf87e8^󰝚  $title  "
fi
